### ISSUE TITLE
NLog is not writing logs to file

### ISSUE THREAD

**Issue by AtaaEddin** [akovac35/LoggingSamples#3]
I have tested 'WebApi' & 'WebApp' with NLog, after couple of requests to see the logs at the console, I exited the App, and there was no logs inside the 'Logs' Folder.

**Comment by akovac35** [comment]
Hi. NLog logs are in the bin/<*>/<*>/Logs folder. E.g. WebApp/bin/Debug/netcoreapp3.1/Logs
The actual location can be made fixed my modifying config files for each logger and providing absolute paths.

**Comment by AtaaEddin** [comment]
Thank you so much, closing this Issue.

**Comment by akovac35** [comment]
A star will be appreciated ;)
